import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-white shadow h-16 flex items-center w-full mb-8 fixed top-0 left-0 right-0 z-50">
          <div className="max-w-6xl mx-auto px-4 w-full flex justify-between h-16 items-center">
            <div className="flex items-center gap-8">
              <a href="/" className="text-xl font-bold" style={{ color: 'var(--primary)' }}>Geoshan Properties Ltd</a>
              <a href="/portfolios" className="text-base font-medium text-gray-700 hover:text-[var(--primary)] transition-colors">Portfolios</a>
            </div>
          </div>
        </nav>
        <div className="max-w-6xl mx-auto px-4 pt-20">
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
