import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full bg-white shadow-sm mb-8">
          <div className="max-w-6xl mx-auto px-4 py-3 flex gap-6 items-center">
            <Link href="/" className="font-semibold text-lg text-blue-700 hover:underline">
              Home
            </Link>
            <Link href="/valuations" className="font-semibold text-lg text-blue-700 hover:underline">
              Saved Valuations
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
