name: Full Stack Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
          pip install pytest
      - name: Run backend tests
        run: |
          cd backend
          . venv/bin/activate
          pytest
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
          npm install --save-dev @types/react-dom
      - name: Run frontend linter
        run: |
          cd frontend
          npm run lint
      - name: Run frontend tests
        run: |
          cd frontend
          npm test 